import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Link } from "expo-router";

import { createLearningRun, getMe, login, register, User, LearningRun, logout } from "@/lib/api";

export default function HomeScreen() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [topic, setTopic] = useState(""); const [hours, setHours] = useState("5");
  const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(false); const [plan, setPlan] = useState<LearningRun | null>(null);
  useEffect(() => { getMe().then(setUser).catch(() => undefined); }, []);
  const signIn = async (mode: "login" | "register") => { setLoading(true); try { setUser(await (mode === "login" ? login(email, password) : register(email, password))); } catch (error) { Alert.alert("Authentication failed", error instanceof Error ? error.message : "Try again."); } finally { setLoading(false); } };
  const generatePlan = async () => { if (topic.trim().length < 2) return Alert.alert("Tell us what you want to learn."); setLoading(true); try { setPlan(await createLearningRun(topic.trim(), Number(hours) || 5)); } catch (error) { Alert.alert("Could not create plan", error instanceof Error ? error.message : "Please try again."); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
    <Text style={styles.eyebrow}>LEARNING COACH</Text><Text style={styles.title}>Build a learning system that adapts to you.</Text>
    {!user ? <View style={styles.card}><Text style={styles.cardTitle}>Sign in to save your plan</Text><TextInput value={email} onChangeText={setEmail} placeholder="Email" autoCapitalize="none" keyboardType="email-address" style={styles.input}/><TextInput value={password} onChangeText={setPassword} placeholder="Password (8+ characters)" secureTextEntry style={styles.input}/><Pressable onPress={() => signIn("login")} style={styles.button}>{loading ? <ActivityIndicator color="#fff"/> : <Text style={styles.buttonText}>Sign in</Text>}</Pressable><Pressable onPress={() => signIn("register")}><Text style={styles.link}>Create an account</Text></Pressable></View> : <>
      <View style={styles.userRow}><Text>Signed in as {user.email}</Text><Pressable onPress={() => logout().then(() => setUser(null))}><Text style={styles.link}>Sign out</Text></Pressable></View>
      {user.role === "admin" && <Link href="/admin" style={styles.adminLink}>Open admin analytics →</Link>}
      <Text style={styles.subtitle}>What do you want to learn? Our agents will research sources, create a schedule, and assess your progress.</Text><TextInput value={topic} onChangeText={setTopic} placeholder="e.g. Python for data analysis" style={styles.input}/><Text style={styles.label}>Hours per week</Text><TextInput value={hours} onChangeText={setHours} keyboardType="number-pad" style={styles.input}/><Pressable onPress={generatePlan} disabled={loading} style={styles.button}>{loading ? <ActivityIndicator color="#fff"/> : <Text style={styles.buttonText}>Create my plan</Text>}</Pressable>
      {plan && <View style={styles.card}><Text style={styles.cardTitle}>Your agent-built curriculum</Text><Text style={styles.summary}>Researcher, Planner, and Examiner sessions are saved securely.</Text>{plan.curriculum.map(item => <View key={item.week} style={styles.week}><Text style={styles.weekTitle}>{item.title}</Text><Text>{item.outcomes.join(" · ")}</Text></View>)}<Text style={styles.weekTitle}>Examiner assignment</Text><Text>{plan.assessment.assignment}</Text><Text style={styles.detail}>Project: {plan.assessment.project}</Text></View>}
    </>}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:"#f7f7fb"},container:{padding:24,gap:12},eyebrow:{color:"#6657d9",fontWeight:"700",letterSpacing:1},title:{fontSize:30,fontWeight:"800",color:"#1d1b2e"},subtitle:{color:"#686579",fontSize:16,lineHeight:23,marginVertical:8},label:{fontWeight:"600",color:"#332f46"},input:{backgroundColor:"#fff",borderColor:"#ddd9ea",borderWidth:1,borderRadius:12,padding:14,fontSize:16},button:{backgroundColor:"#6657d9",borderRadius:12,minHeight:52,alignItems:"center",justifyContent:"center",marginTop:4},buttonText:{color:"#fff",fontWeight:"700",fontSize:16},card:{backgroundColor:"#fff",borderRadius:16,padding:16,marginTop:12,gap:10},cardTitle:{fontSize:21,fontWeight:"800",color:"#1d1b2e"},summary:{color:"#686579"},week:{borderTopColor:"#eceaf3",borderTopWidth:1,paddingTop:12,gap:5},weekTitle:{fontWeight:"700",color:"#332f46"},detail:{color:"#565166",lineHeight:20},link:{color:"#6657d9",fontWeight:"700",textAlign:"center",padding:6},adminLink:{color:"#4234ae",fontWeight:"800",paddingVertical:6},userRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"} });
