import { BookOpen, CheckCircle2, ExternalLink, ListTree, Telescope } from "lucide-react";
import type { LearningRun } from "@/lib/api";
import { Card } from "@/components/ui/card";

function externalUrl(value: string) { try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:" ? url.toString() : undefined; } catch { return undefined; } }

export function OutlineView({ run }: { run: LearningRun }) {
  return <section aria-labelledby="outline-title" className="grid gap-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Generated outline</p><h2 id="outline-title" className="mt-1 text-2xl font-bold">Your path for {run.research.topic}</h2><p className="mt-1 text-sm text-muted-foreground">Built with the {run.provider} research workflow. Review sources before relying on them.</p></div><span className="rounded-full bg-accent px-3 py-1 text-sm font-semibold">{run.curriculum.length} modules</span></div>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_20rem]">
      <Card className="p-0"><ol className="divide-y" aria-label="Course modules">{run.curriculum.map((module, index) => <li key={`${module.week}-${module.title}`} className="p-5"><div className="flex gap-4"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-accent text-sm font-bold text-primary">{module.week}</div><div><h3 className="font-bold">{module.title}</h3>{index > 0 && <p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><ListTree size={15} aria-hidden="true" /> Prerequisite: Module {run.curriculum[index - 1].week}</p>}<ul className="mt-3 grid gap-1.5 text-sm">{module.outcomes.map((outcome) => <li key={outcome} className="flex gap-2"><CheckCircle2 className="mt-0.5 shrink-0 text-primary" size={16} aria-hidden="true" />{outcome}</li>)}</ul></div></div></li>)}</ol></Card>
      <div className="grid content-start gap-4"><Card><h3 className="flex items-center gap-2 font-bold"><Telescope size={18} className="text-primary" aria-hidden="true" />Research basis</h3><p className="mt-2 text-sm text-muted-foreground">{run.research.sources.length} sources surfaced for this outline. Source provenance will expand as the registry API arrives.</p></Card><Card><h3 className="flex items-center gap-2 font-bold"><BookOpen size={18} className="text-primary" aria-hidden="true" />First check</h3><p className="mt-2 text-sm text-muted-foreground">{run.assessment.quiz[0] ?? "Knowledge checks will appear here."}</p></Card></div>
    </div>
    <Card><h3 className="text-lg font-bold">Sources</h3><ul className="mt-4 grid gap-3 md:grid-cols-2">{run.research.sources.map((source) => { const href = externalUrl(source.url); return <li key={`${source.title}-${source.url}`} className="rounded-lg border p-3"><p className="font-semibold">{source.title}</p><p className="mt-1 text-sm text-muted-foreground">{source.rationale}</p>{href && <a href={href} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-sm font-semibold text-primary underline-offset-4 hover:underline">Open source <ExternalLink size={14} aria-hidden="true" /></a>}</li>; })}</ul></Card>
  </section>;
}
